services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped

    user: "1000:1000" # sudo usermod -aG render, sudo usermod -aG video to add your user to the render and video groups for hardware acceleration, you can check if your user is in those groups with ```groups```

    group_add:
      - "922" # run, ```getent group render | cut -d: -f3``` to get the GID for render group
      - "44" # run ```getent group video | cut -d: -f3``` for video group, add both if you want hardware acceleration
    ports:
      - "8096:8096"
      - "7359:7359/udp"
    volumes:
      - ./config:/config
      - ./cache:/cache
      
      # CIFS mounts
      - "truenas_blu-ray:/data/truenas_blu-ray:ro"
      - "truenas_dvd:/data/truenas_dvd:ro"
      - "truenas_erai-raws:/data/truenas_erai-raws:ro"

    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # docker exec -it jellyfin /usr/lib/jellyfin-ffmpeg/vainfo --display drm --device /dev/dri/renderD128 to check if hardware acceleration is working, you should see "VAProfileH264Main" or similar in the output
      - /dev/dri/card0:/dev/dri/card0 # docker exec -it jellyfin /usr/lib/jellyfin-ffmpeg/ffmpeg -v debug -init_hw_device vulkan to check if hardware acceleration is working, you should see "Vulkan driver found" in the output

#Architecture:                x86_64
#  CPU op-mode(s):            32-bit, 64-bit
#  Address sizes:             48 bits physical, 48 bits virtual
#  Byte Order:                Little Endian
#CPU(s):                      16
#  On-line CPU(s) list:       0-15
#Vendor ID:                   AuthenticAMD
#  Model name:                AMD Ryzen 7 7730U with Radeon Graphics

#Trying display: drm
#libva info: VA-API version 1.22.0
#libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
#libva info: Found init function __vaDriverInit_1_22
#libva info: va_openDriver() returns 0
#vainfo: VA-API version: 1.22 (libva 2.22.0)
#vainfo: Driver version: Mesa Gallium driver 25.2.6-1~bpo13+1 for AMD Radeon Graphics (radeonsi, renoir, ACO, DRM 3.64, 6.18.9+deb13-amd64)
#vainfo: Supported profile and entrypoints
#      VAProfileMPEG2Simple            : VAEntrypointVLD
#      VAProfileMPEG2Main              : VAEntrypointVLD
#      VAProfileVC1Simple              : VAEntrypointVLD
#      VAProfileVC1Main                : VAEntrypointVLD
#      VAProfileVC1Advanced            : VAEntrypointVLD
#      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
#      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
#      VAProfileH264Main               : VAEntrypointVLD
#      VAProfileH264Main               : VAEntrypointEncSlice
#      VAProfileH264High               : VAEntrypointVLD
#      VAProfileH264High               : VAEntrypointEncSlice
#      VAProfileHEVCMain               : VAEntrypointVLD
#      VAProfileHEVCMain               : VAEntrypointEncSlice
#      VAProfileHEVCMain10             : VAEntrypointVLD
#      VAProfileHEVCMain10             : VAEntrypointEncSlice
#      VAProfileJPEGBaseline           : VAEntrypointVLD
#      VAProfileVP9Profile0            : VAEntrypointVLD
#      VAProfileVP9Profile2            : VAEntrypointVLD
#      VAProfileNone                   : VAEntrypointVideoProc
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr
    ports:
      - 5690:5690
    volumes:
      - ./appdata:/data
    environment:
      - PUID=1000 # Set UID
      - PGID=1000  # Set GID
      - DISABLE_BUILTIN_AUTH=false # Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=America/Chicago # Set your timezone here

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "9292:80"
    volumes:
      - ./filebrowser.db:/database/filebrowser.db
      - ./filebrowser-config:/config

      # Same CIFS mounts as Jellyfin
      - truenas_blu-ray:/srv/truenas_blu-ray:ro
      - truenas_dvd:/srv/truenas_dvd:ro
      - truenas_erai-raws:/srv/truenas_erai-raws:ro

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago

volumes:
  truenas_blu-ray:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.8.2/Blu-ray
      o: username=${TrueNAS_SMB_USER},password=${TrueNAS_SMB_PASS},file_mode=0777,dir_mode=0777,ro

  truenas_dvd:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.8.2/dvd
      o: username=${TrueNAS_SMB_USER},password=${TrueNAS_SMB_PASS},file_mode=0777,dir_mode=0777,ro

  truenas_erai-raws:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.8.2/Erai-raws
      o: username=${TrueNAS_SMB_USER},password=${TrueNAS_SMB_PASS},file_mode=0777,dir_mode=0777,ro
