services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped

    user: "1000:1000" # sudo usermod -aG render, sudo usermod -aG video to add your user to the render and video groups for hardware acceleration, you can check if your user is in those groups with ```groups```

    group_add:
      - "922" # run, ```getent group render | cut -d: -f3``` to get the GID for render group
      - "44" # run ```getent group video | cut -d: -f3``` for video group, add both if you want hardware acceleration
    ports:
      - "8096:8096"
      - "7359:7359/udp"
    volumes:
      - ./config:/config
      - ./cache:/cache
      
      # CIFS mounts
      - "truenas_blu-ray:/data/truenas_blu-ray:ro"
      - "truenas_dvd:/data/truenas_dvd:ro"
      - "truenas_erai-raws:/data/truenas_erai-raws:ro"

    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # docker exec -it jellyfin /usr/lib/jellyfin-ffmpeg/vainfo --display drm --device /dev/dri/renderD128 to check if hardware acceleration is working, you should see "VAProfileH264Main" or similar in the output
      - /dev/dri/card0:/dev/dri/card0 # docker exec -it jellyfin /usr/lib/jellyfin-ffmpeg/ffmpeg -v debug -init_hw_device vulkan to check if hardware acceleration is working, you should see "Vulkan driver found" in the output

  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr
    ports:
      - 5690:5690
    volumes:
      - ./appdata:/data
    environment:
      - PUID=1000 # Set UID
      - PGID=1000 # Set GID
      - DISABLE_BUILTIN_AUTH=false # Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=America/Chicago # Set your timezone here

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "9292:80"
    volumes:
      - ./filebrowser.db:/database/filebrowser.db
      - ./filebrowser-config:/config

      # Same CIFS mounts as Jellyfin
      - truenas_blu-ray:/srv/truenas_blu-ray:ro
      - truenas_dvd:/srv/truenas_dvd:ro
      - truenas_erai-raws:/srv/truenas_erai-raws:ro

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago

volumes:
  truenas_blu-ray:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.8.2/Blu-ray
      o: username=${TrueNAS_SMB_USER},password=${TrueNAS_SMB_PASS},file_mode=0777,dir_mode=0777,ro

  truenas_dvd:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.8.2/dvd
      o: username=${TrueNAS_SMB_USER},password=${TrueNAS_SMB_PASS},file_mode=0777,dir_mode=0777,ro

  truenas_erai-raws:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.8.2/Erai-raws
      o: username=${TrueNAS_SMB_USER},password=${TrueNAS_SMB_PASS},file_mode=0777,dir_mode=0777,ro
